#!/usr/bin/env python3
"""Compile per-stack governance rules from the shared core.

A stack declares in its govbuild.json which rule files come from core/rules/,
which variables to substitute, and which sections its overlay replaces.
Generated files must never be edited by hand: run `govctl build` instead.
"""

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CORE_RULES = ROOT / "core" / "rules"
POLICIES = ROOT / "policies"
MANIFEST_NAME = "govbuild.json"
MARKER = "<!-- Generated by tools/govctl from core/rules/{source} — edit the source, not this file. -->"
POLICY_MARKER = (
    "<!-- Generated by tools/govctl from policies/{domain}/ — edit the policy, not this file. -->"
)
POLICY_REQUIRED_KEYS = ("id", "title", "heading", "severity", "enforcement")
SEVERITIES = ("critical", "high", "medium", "low")
VAR_RE = re.compile(r"\{\{([A-Z0-9_]+)\}\}")
HEADING_RE = re.compile(r"^## (.+)$")


class BuildError(Exception):
    pass


def split_frontmatter(text):
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---\n", 4)
    if end == -1:
        return "", text
    return text[: end + 5], text[end + 5 :]


def split_sections(body):
    """Return (preamble, [(heading, section_text)]) where section_text keeps its heading."""
    lines = body.splitlines(keepends=True)
    preamble, sections, current, heading = [], [], None, None
    for line in lines:
        match = HEADING_RE.match(line.rstrip("\n"))
        if match:
            if current is not None:
                sections.append((heading, "".join(current)))
            heading, current = match.group(1).strip(), [line]
        elif current is None:
            preamble.append(line)
        else:
            current.append(line)
    if current is not None:
        sections.append((heading, "".join(current)))
    return "".join(preamble), sections


def substitute(text, variables, origin):
    missing = {name for name in VAR_RE.findall(text) if name not in variables}
    if missing:
        raise BuildError(f"{origin}: undefined variable(s) {sorted(missing)}")
    return VAR_RE.sub(lambda m: variables[m.group(1)], text)


def requirements_of(policy):
    """Every requirement of a policy, core, server-scoped and stack-bound."""
    items = list(policy.get("requirements") or []) + list(policy.get("server_requirements") or [])
    for binding in (policy.get("stacks") or {}).values():
        items += list(binding.get("requirements") or [])
    return items


def load_policies(domain):
    """Load and validate every policy of a domain, ordered by id."""
    domain_dir = POLICIES / domain
    if not domain_dir.is_dir():
        raise BuildError(f"unknown policy domain '{domain}' (expected {domain_dir})")

    policies = []
    for policy_path in sorted(domain_dir.glob("*.yml")):
        policy = yaml.safe_load(policy_path.read_text())
        missing = [key for key in POLICY_REQUIRED_KEYS if key not in policy]
        if missing:
            raise BuildError(f"{policy_path.name}: missing key(s) {missing}")
        if not policy_path.name.startswith(policy["id"]):
            raise BuildError(f"{policy_path.name}: filename does not start with id {policy['id']}")
        if policy["severity"] not in SEVERITIES:
            raise BuildError(f"{policy_path.name}: severity must be one of {list(SEVERITIES)}")
        for requirement in requirements_of(policy):
            if not isinstance(requirement, str):
                raise BuildError(
                    f"{policy_path.name}: requirement is not a string — quote it: {requirement!r}"
                )
        policies.append(policy)

    if not policies:
        raise BuildError(f"no policy found in {domain_dir}")
    return policies


def render_from_policies(rule_name, spec, stack_dir, serves_http=False):
    """Render a stack rule file from the policies of a domain, keeping only bound policies."""
    domain = spec["from_policies"]
    stack = stack_dir.name
    for key in ("title", "paths"):
        if key not in spec:
            raise BuildError(f"{stack}/{rule_name}: '{key}' is required with 'from_policies'")

    frontmatter = "---\npaths:\n" + "".join(
        f"  - {json.dumps(pattern)}\n" for pattern in spec["paths"]
    ) + "---\n"

    chunks = [f"# {spec['title']}\n"]
    bound = 0
    for policy in load_policies(domain):
        binding = (policy.get("stacks") or {}).get(stack)
        if binding is None or binding.get("applies") is False:
            continue
        if not policy.get("enforcement", {}).get("agent", True):
            continue
        bound += 1
        lines = [f"## {policy['id']} — {policy['heading']}\n"]
        requirements = list(policy.get("requirements") or [])
        if serves_http:
            requirements += list(policy.get("server_requirements") or [])
        requirements += list(binding.get("requirements") or [])
        if not requirements:
            raise BuildError(f"{policy['id']}: no requirement to render for stack '{stack}'")
        lines += [f"- {requirement}\n" for requirement in requirements]
        if binding.get("example"):
            lines.append("\n" + binding["example"].strip() + "\n")
        chunks.append("".join(lines))

    if not bound:
        raise BuildError(f"{stack}/{rule_name}: no policy of domain '{domain}' binds this stack")

    marker = POLICY_MARKER.format(domain=domain)
    return frontmatter + marker + "\n\n" + "\n".join(chunks)


def render(rule_name, spec, stack_dir):
    source = spec.get("source", rule_name)
    core_path = CORE_RULES / source
    if not core_path.is_file():
        raise BuildError(f"{stack_dir.name}/{rule_name}: missing core source {source}")

    frontmatter, body = split_frontmatter(core_path.read_text())
    preamble, sections = split_sections(body)

    overlay_ref = spec.get("overlay")
    if overlay_ref:
        overlay_path = stack_dir / overlay_ref
        if not overlay_path.is_file():
            raise BuildError(f"{stack_dir.name}/{rule_name}: missing overlay {overlay_ref}")
        _, overlay_body = split_frontmatter(overlay_path.read_text())
        _, overlay_sections = split_sections(overlay_body)
        known = {heading for heading, _ in sections}
        replacements = {}
        for heading, text in overlay_sections:
            if heading not in known:
                raise BuildError(
                    f"{overlay_ref}: section '## {heading}' does not exist in core/rules/{source}"
                )
            replacements[heading] = text
        sections = [(heading, replacements.get(heading, text)) for heading, text in sections]

    rendered = frontmatter + MARKER.format(source=source) + "\n" + preamble + "".join(
        text for _, text in sections
    )
    return substitute(rendered, spec.get("vars", {}), f"{stack_dir.name}/{rule_name}")


def manifests(stack_filter=None):
    found = sorted(ROOT.glob(f"*/{MANIFEST_NAME}"))
    if stack_filter:
        found = [path for path in found if path.parent.name == stack_filter]
        if not found:
            raise BuildError(f"no {MANIFEST_NAME} found for stack '{stack_filter}'")
    return found


def targets(manifest_path):
    stack_dir = manifest_path.parent
    manifest = json.loads(manifest_path.read_text())
    serves_http = manifest.get("serves_http", False)
    for rule_name, spec in manifest.get("rules", {}).items():
        if spec.get("own"):
            continue
        if spec.get("from_policies"):
            content = render_from_policies(rule_name, spec, stack_dir, serves_http)
        else:
            content = render(rule_name, spec, stack_dir)
        yield stack_dir, rule_name, content


def run(stack_filter, check_only):
    written, stale = 0, []
    for manifest_path in manifests(stack_filter):
        for stack_dir, rule_name, content in targets(manifest_path):
            out = stack_dir / ".claude" / "rules" / rule_name
            current = out.read_text() if out.is_file() else ""
            if current == content:
                continue
            relative = out.relative_to(ROOT)
            if check_only:
                stale.append((relative, current, content))
            else:
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(content)
                print(f"built {relative}")
                written += 1

    if check_only:
        for relative, current, content in stale:
            print(f"stale: {relative}", file=sys.stderr)
            sys.stderr.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=f"{relative} (on disk)",
                    tofile=f"{relative} (expected)",
                )
            )
        if stale:
            print(
                f"\n{len(stale)} generated rule file(s) out of date — run `tools/govctl build`.",
                file=sys.stderr,
            )
            return 1
        print("all generated rule files are up to date")
        return 0

    print(f"{written} file(s) written" if written else "nothing to do — already up to date")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Compile governance rules from the shared core.")
    parser.add_argument("command", choices=["build", "check"])
    parser.add_argument("--stack", help="limit to a single stack folder")
    args = parser.parse_args()
    try:
        return run(args.stack, args.command == "check")
    except BuildError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
