#!/usr/bin/env python3
"""Compile per-stack governance rules from the shared core.

A stack declares in its govbuild.json which rule files come from core/rules/,
which variables to substitute, and which sections its overlay replaces.
Generated files must never be edited by hand: run `govctl build` instead.
"""

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE_RULES = ROOT / "core" / "rules"
MANIFEST_NAME = "govbuild.json"
MARKER = "<!-- Generated by tools/govctl from core/rules/{source} — edit the source, not this file. -->"
VAR_RE = re.compile(r"\{\{([A-Z0-9_]+)\}\}")
HEADING_RE = re.compile(r"^## (.+)$")


class BuildError(Exception):
    pass


def split_frontmatter(text):
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---\n", 4)
    if end == -1:
        return "", text
    return text[: end + 5], text[end + 5 :]


def split_sections(body):
    """Return (preamble, [(heading, section_text)]) where section_text keeps its heading."""
    lines = body.splitlines(keepends=True)
    preamble, sections, current, heading = [], [], None, None
    for line in lines:
        match = HEADING_RE.match(line.rstrip("\n"))
        if match:
            if current is not None:
                sections.append((heading, "".join(current)))
            heading, current = match.group(1).strip(), [line]
        elif current is None:
            preamble.append(line)
        else:
            current.append(line)
    if current is not None:
        sections.append((heading, "".join(current)))
    return "".join(preamble), sections


def substitute(text, variables, origin):
    missing = {name for name in VAR_RE.findall(text) if name not in variables}
    if missing:
        raise BuildError(f"{origin}: undefined variable(s) {sorted(missing)}")
    return VAR_RE.sub(lambda m: variables[m.group(1)], text)


def render(rule_name, spec, stack_dir):
    source = spec.get("source", rule_name)
    core_path = CORE_RULES / source
    if not core_path.is_file():
        raise BuildError(f"{stack_dir.name}/{rule_name}: missing core source {source}")

    frontmatter, body = split_frontmatter(core_path.read_text())
    preamble, sections = split_sections(body)

    overlay_ref = spec.get("overlay")
    if overlay_ref:
        overlay_path = stack_dir / overlay_ref
        if not overlay_path.is_file():
            raise BuildError(f"{stack_dir.name}/{rule_name}: missing overlay {overlay_ref}")
        _, overlay_body = split_frontmatter(overlay_path.read_text())
        _, overlay_sections = split_sections(overlay_body)
        known = {heading for heading, _ in sections}
        replacements = {}
        for heading, text in overlay_sections:
            if heading not in known:
                raise BuildError(
                    f"{overlay_ref}: section '## {heading}' does not exist in core/rules/{source}"
                )
            replacements[heading] = text
        sections = [(heading, replacements.get(heading, text)) for heading, text in sections]

    rendered = frontmatter + MARKER.format(source=source) + "\n" + preamble + "".join(
        text for _, text in sections
    )
    return substitute(rendered, spec.get("vars", {}), f"{stack_dir.name}/{rule_name}")


def manifests(stack_filter=None):
    found = sorted(ROOT.glob(f"*/{MANIFEST_NAME}"))
    if stack_filter:
        found = [path for path in found if path.parent.name == stack_filter]
        if not found:
            raise BuildError(f"no {MANIFEST_NAME} found for stack '{stack_filter}'")
    return found


def targets(manifest_path):
    stack_dir = manifest_path.parent
    manifest = json.loads(manifest_path.read_text())
    for rule_name, spec in manifest.get("rules", {}).items():
        if spec.get("own"):
            continue
        yield stack_dir, rule_name, render(rule_name, spec, stack_dir)


def run(stack_filter, check_only):
    written, stale = 0, []
    for manifest_path in manifests(stack_filter):
        for stack_dir, rule_name, content in targets(manifest_path):
            out = stack_dir / ".claude" / "rules" / rule_name
            current = out.read_text() if out.is_file() else ""
            if current == content:
                continue
            relative = out.relative_to(ROOT)
            if check_only:
                stale.append((relative, current, content))
            else:
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(content)
                print(f"built {relative}")
                written += 1

    if check_only:
        for relative, current, content in stale:
            print(f"stale: {relative}", file=sys.stderr)
            sys.stderr.writelines(
                difflib.unified_diff(
                    current.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=f"{relative} (on disk)",
                    tofile=f"{relative} (expected)",
                )
            )
        if stale:
            print(
                f"\n{len(stale)} generated rule file(s) out of date — run `tools/govctl build`.",
                file=sys.stderr,
            )
            return 1
        print("all generated rule files are up to date")
        return 0

    print(f"{written} file(s) written" if written else "nothing to do — already up to date")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Compile governance rules from the shared core.")
    parser.add_argument("command", choices=["build", "check"])
    parser.add_argument("--stack", help="limit to a single stack folder")
    args = parser.parse_args()
    try:
        return run(args.stack, args.command == "check")
    except BuildError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
